import logging
from datetime import datetime
from pathlib import Path

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def generate_moc(base_dir: Path) -> None:
    concepts_dir = base_dir / "03_Concepts"
    moc_file = base_dir / "00_Map_of_Content.md"

    if not concepts_dir.exists():
        logging.error(f"Concepts directory missing at {concepts_dir}. Run assimilation first.")
        return

    concept_files = list(concepts_dir.glob("*.md"))
    if not concept_files:
        logging.warning("No concept notes found. MoC will be empty.")

    concept_files.sort()

    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    moc_content = f"# Master Map of Content (MoC)\n\n*Auto-generated by automation agent on: {timestamp}*\n\n## Assimilated Concepts\n\n"

    for index, filepath in enumerate(concept_files):
        note_title = filepath.stem
        moc_content += f"{index + 1}. [[{note_title}]]\n"

    try:
        with open(moc_file, 'w', encoding='utf-8') as f:
            f.write(moc_content)
        logging.info(f"Successfully generated Map of Content at {moc_file.name}")
    except IOError as e:
        logging.error(f"Failed to write MoC file: {e}")

if __name__ == "__main__":
    current_directory = Path.cwd()
    logging.info("Initiating automated Map of Content generation...")
    generate_moc(current_directory)
    logging.info("MoC pipeline complete. The robots have mapped your thoughts.")
